### ISSUE TITLE
Add name field to mailing list sign up and add a note to check email for spam

### ISSUE THREAD

**Issue by MandyMeindersma** [devedmonton/devedmonton.com#131]
What we would like:

1. Add an input box for first name to send to mailchimp
2. Add a note to check email for spam
    - When i did some tests to sign up for the list I found the confirmation email was getting sent to my spam. I want to add to `We have sent an email to mmeindersma@dotdash.com with a link to confirm your subscription.` Perhaps just another sentence like `Please check your spam folder!`

cc: @DerrykBoyd

**Comment by DerrykBoyd** [comment]
@MandyMeindersma do you know how mailchimp accepts the name? There's no dedicated field for that in the API https://mailchimp.com/developer/marketing/api/list-members/add-member-to-list/ 

Only thing I can see there is maybe the merge_variable, but that might need setup

**Comment by MandyMeindersma** [comment]
You were right about merge variable! It worked with no set up!
