### ISSUE TITLE
Drop the Slack inviter app and just use an invite link

### ISSUE THREAD

**Issue by MarkBennett** [devedmonton/devedmonton.com#146]
At some point since the website launched Slack has added the ability to create invite links that don't expire.

Given that Heroku is going to charge soon, and that we can now create a permanent invite link, I propose that we:

1. Delete the Heroku inviter app
2. Update the "Join our Slack" link to use a permanent invite link instead.

You can [read about how to create a permanent link in the Slack docs](https://slack.com/help/articles/201330256-Invite-new-members-to-your-workspace#:~:text=Desktop%20iOS%20Android-,Select%20Invite%20people%20to%20%5Bworkspace%20name%5D%20from%20the%20menu.,when%20someone%20uses%20your%20link.), but I created one that's ready to go if anyone wants to take this on. I can do a PR after work if there's interest:

https://join.slack.com/t/devedmonton/shared_invite/zt-1h0s5j0g4-ntARRvWGapJcnckM34jdZw

**Comment by jon-at-rithmik** [comment]
I have no real skin in the game, but as an infrastructure guy I'm always happy to see "decommission the thing we don't need" proposed!

Technical nit: probably should do 2 before 1, or some new member may get unlucky in their attempt to join.

**Comment by MarkBennett** [comment]
Good point @jon-at-rithmik. I've tested the invite link myself, but a few others might want to do the same before we switch over to it...

https://join.slack.com/t/devedmonton/shared_invite/zt-1g5tyn7c1-JaTgK4Mf7HvO9LAgaXvt7g

**Comment by MarkBennett** [comment]
> I tried signing up using an alternate email in an incognito window ![image](https://user-images.githubusercontent.com/5544472/189971811-e9bd5e72-1786-4f63-a483-e1c109918219.png)

Hmm... annoying it doesn't tell you anymore than that! I assume that appears after you've entered your email and submitted the form?

**Comment by MandyMeindersma** [comment]
Another issue I see with this is that is says that link is only valid for 100 invites? What happens after the 100?

![image](https://user-images.githubusercontent.com/17459171/189980959-b061c8d9-eed1-4f60-be57-0f4d0afabbe1.png)

**Comment by acenasir** [comment]
Yes signed in using oauth @MarkBennett

**Comment by MarkBennett** [comment]
> Yes signed in using oauth @MarkBennett 

Hmm, I'm at work but will look into this when I have a moment.

**Comment by MarkBennett** [comment]
Finally had some time to circle back on this... I deactivated the old link completely and made a new one that's set to never expire.

https://join.slack.com/t/devedmonton/shared_invite/zt-1h0s5j0g4-ntARRvWGapJcnckM34jdZw

I was then able to use it to join using my Google account.

@acenasir, can you try and see if this one works for you?

**Comment by acenasir** [comment]
Worked Smoothly this time around. Thanks @MarkBennett
