### ISSUE TITLE
Add a subscription form that adds emails to our DES mailing list

### ISSUE THREAD

**Issue by MarkBennett** [devedmonton/devedmonton.com#43]
# Acceptance Criteria
1. Add a form to the home page that lets users subscribe to [our mailing list for announcements about DES events and news](https://groups.google.com/u/3/a/devedmonton.com/g/mailing-list)
1. Form should work on mobile and desktop

# Background
We're trying to build out a mailing list to better include people not on Slack. Google Groups is terrible for integration, but it does make managing events in Google Calendar easy, and let's us use our DES Google Workspace to manage permissions so it's what we've decided to use.

The easiest way I've seen so far to get a form working is to set up a Netlify function that accepts the form submission. It will handle redirecting to a success page after the user is added.

The Netlify function uses [the Google Directory API](https://developers.google.com/admin-sdk/directory/v1/guides/manage-group-members) to add the email to a Google Group.

For styling, it looks like [Tailwind UI includes a newletter section](https://tailwindui.com/components/marketing/sections/newsletter-sections) which we could cut-and-paste as is.

**Comment by dboydgit** [comment]
I can probably set this up, would need more info though. That first link to the google group doesn't work for me @MarkBennett

**Comment by MandyMeindersma** [comment]
@dboydgit The link works fine for me, I think it works because I am a DES memeber and mark added me to the des group?

**Comment by dboydgit** [comment]
> @dboydgit The link works fine for me, I think it works because mark added me to the des group?

Got it working now thanks, the u/2 in the link was kicking me into a different account from my default.

**Comment by MarkBennett** [comment]
I've just changed the mailing list link we want to use for this. It now points here:

https://groups.google.com/u/3/a/devedmonton.com/g/mailing-list

The old link was to the mailing list we just agreed to use only for sending out formal notice to our members. This mailing list should just be for anyone who wants to get regular communication from DES by email and isn't neccesarily a member themselves (meetup attendees, students, employers, etc.)

**Comment by dboydgit** [comment]
@MarkBennett I'm looking into that Google Directory API, and it looks like it only applies to Google Workspace accounts (their business version) and not consumer accounts. Does devedmonton have a business google account?

**Comment by MarkBennett** [comment]
> @MarkBennett I'm looking into that Google Directory API, and it looks like it only applies to Google Workspace accounts (their business version) and not consumer accounts. Does devedmonton have a business google account?

We do have a Workspace account yes. Any @devddmonton.com email would be part of it.

What needs to be set up? Just the service account with permission to edit the group membership for the list?

**Comment by MarkBennett** [comment]
🎉
