### ISSUE TITLE
Add board members and maybe members (?) to the webiste

### ISSUE THREAD

**Issue by MandyMeindersma** [devedmonton/devedmonton.com#64]
TODO 

- [x] Remove board recruitment banner
- [x] Remove board application links/buttons and copy from the board_recruitment page
- [x] Add the newly elected board to a new "board" page
- [x] Change the link in the menu to point to the board page

**Comment by MandyMeindersma** [comment]
Maybe just a society page off the front page to make board and membership clear. (idea from @abramhindle )

**Comment by dboydgit** [comment]
@MandyMeindersma we already have a board page, which was setup for recruiting. Now that the new board is confirmed I think we can repurpose that page to list the new board. I think for listing members we can move that to a separate discussion as that involves a bit more ongoing effort and would probably need someone to commit to keeping the list up to date.

I think we can also add onto this issue the removal of the board recruiting copy.

**Comment by dboydgit** [comment]
Closing this issue as we have a basic board info page up. We can create a new issue for updating the board information / bios with the new roles.
