### ISSUE TITLE
Add link to allow people to become DES members

### ISSUE THREAD

**Issue by MarkBennett** [devedmonton/devedmonton.com#66]
We'll need to be careful about how this is framed, as you don't need to be a member to:

1. Join the Slack
2. Attend or participate in events
3. Attend or talk at monthly DES meetings
4. Join mailing list

You only need to be a member if you:

1. Want to be able to vote on motions at the monthly meetings
2. Want to use our streaming accounts or other equipment
3. Really like what DES does and want to support us with $20/year!!

The copy we use for this should probably go on the registration form itself, and be echoed on the website.

To become a member you need to complete this form:

https://docs.google.com/forms/d/e/1FAIpQLSdHuLt6NOuHIyLIXXdM6hf6TzlbG8VInLZe5E3M7pvwZrNHEQ/viewform?usp=sf_link

And then send $20 to memberships@devedmonton.com via interac (preferred) or PayPal.

**Comment by MandyMeindersma** [comment]
fixed in https://github.com/devedmonton/devedmonton.com/pull/135
