### ISSUE TITLE
Add a thank you to Clubhouse.io on the Sponsors page

### ISSUE THREAD

**Issue by MarkBennett** [devedmonton/devedmonton.com#88]
# Acceptance Criteria
1. Clubhouse should be thanked on https://devedmonton.com/sponsors
2. We should use the Clubhouse branding guide on https://brand.clubhouse.io/

**Comment by MandyMeindersma** [comment]
@blerg-rush  sorry for not seeing your question. Github has not been notifying me properly. 

Did you mean this? https://devedmonton.com/sponsors
