### ISSUE TITLE
Add a quick introduction to the Slack to our website

### ISSUE THREAD

**Issue by MandyMeindersma** [devedmonton/devedmonton.com#99]
This will be a lot similar to the intro message we have set up on the slack. 

- Cover details from the welcome message for anyone who's forgotten
- Link to the Code of Conduct
- Link to the job posting details
- List important channels (like those from the welcome message but also meetups, etc.)

**Comment by MarkBennett** [comment]
So from what I'm seeing of the discussion on the PR, can we add to the acceptance criteria:

1) A link to more information and to join the Slack above the fold on mobile and desktop

It sounds like there's not concensus on if Slack needs it's own page. Can we agree to leave that out for now and to try to ship this PR as is then iterate on it later. It's easy to move the Slack section to it's own page if the homepage gets to busy and it would be nice to get this out there! :)

**Comment by MandyMeindersma** [comment]
Dan's pr I think does that? Unless you mean something that i don't understand:
![image](https://user-images.githubusercontent.com/17459171/139712269-bac6a722-d64a-4456-829c-bfb2f7057927.png)

and then that links to the little section he made
